apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault-agent-inject-example
spec:
  selector:
    matchLabels:
      app: vault-agent-inject-example
  template:
    metadata:
      labels:
        app: vault-agent-inject-example
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-secret-hello.txt: /secret/data/hello
        vault.hashicorp.com/role: app
        vault.hashicorp.com/tls-skip-verify: 'true'
    spec:
      containers:
      - name: debian
        image: debian:latest
        command: [sleep, infinity]
      serviceAccountName: default
