apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: spring-boot
  ports:
    - port: 3306
      targetPort: 3306
  externalIPs:
    - 192.168.0.133
  type: LoadBalancer
