apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
        - name: app
          image: krzysztofpol/spring-boot-appl:tomcat_mysql_service
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_URL
              value: jdbc:mysql://mysql-service/seconddb
            - name: MYSQL_USER
              value: root
            - name: MYSQL_PASS
              valueFrom:
               secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD 
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: spring-boot
spec:
  selector:
    app: spring-boot
  ports:
    - port: 80
      targetPort: 8080
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
 name: mysql-secret
type: Opaque
data:
 MYSQL_PASSWORD: IUNlbHQxMjM=
